{% set version = "2.1.2" %}

package:
  name: doxyrest
  version: {{ version }}

source:
  url: https://github.com/vovkos/doxyrest_b/releases/download/doxyrest-{{ version }}/doxyrest-{{ version }}-src.tar.xz
  sha256: 14a6b8ae38bee552012365f2de0b96cd52d674e0754ca761180332c7859df064

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ragel

  host:
    - expat
    - lua

  run:
    - expat
    - lua

test:
  commands:
    - doxyrest --help

about:
  home: https://github.com/vovkos/doxyrest/
  license: MIT
  license_file: LICENSE.txt
  summary: A Doxygen-to-RestructuredText compiler

extra:
  recipe-maintainers:
    - vovkos
