travis:
  secure:
    BINSTAR_TOKEN: u2O/78OgxeWxUQ/DUBbxjseH9czatbeR3au8u4z7pZqMF7QEV2GFH2VwV3DHhUT6kt7s+QZmszDYCGWwWDovoPAeUpJF9WWY0pUpwPC/ZVGOJNZfRDnpTsRkNn0V9BILVO2bUjPUEVHbVdXKX/jcHSz0Gz9iM3Tho4XhWcaTKxLoV4B4FrhlQ25/ghgId68dvWrNePvNBsAaO573H/AD5poOVb7vGL3RltyMC+y1KsqXZS/0sOcEDtS84ozXUlzKEq3BkdSSzS3CSjoJsHtcm6aF5E1HXPx4bfwTbTvAbGxUBxou7YzXbDypiiAPu1dwJl1oDnm+EWDPI5hsXU5OU6URk9D9nYnK7eV4t7MZKBfBkCB7wf4ph1Fle4p0V7CcHuQ1OoppqybBeQIVDMK6pqphyLX08awYKbpy/t+WUgCN+NKDHuARz7o3xkXPUr4T2avWXCDek77hmjqAreC2CreBPs3d4DAAglOEvEJ/FV/rCpqyHG5tyv6QxklIG8wKAWmnwzp+1k2nf6N9mKtSsIyjuZSM6Y60YPTrzdBtBJ9Z6+gO7xOtSiuAZbirPdSCNKpcJx0xLvJYWYt/Bqo/Ab+sFBcNXf4XykAj+uFzo2BLTzfM4yFcLAUbiSfVjESyATaoVYFcay45x8O8RUDOt0iDzvWfqPWN18DggFT11iU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
